import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import {
  Schema as MongooseSchema,
  Types,
  type HydratedDocument,
} from "mongoose";

/**
 * A saved card.
 *
 * Exactly one of `owner` and `guestId` is set — a design belongs to an account
 * or to a browser, never both and never neither. Signing in moves it from the
 * second to the first.
 *
 * The client's own `createdAt`/`updatedAt` are stored verbatim, because they
 * are what decides whether the copy in the browser or the copy here is newer.
 * Mongoose keeps its own pair under different names so the two cannot be
 * confused: one is the document's history, the other is the row's.
 */
@Schema({
  versionKey: false,
  timestamps: { createdAt: "serverCreatedAt", updatedAt: "serverUpdatedAt" },
})
export class Design {
  @Prop({ type: Types.ObjectId, ref: "User", default: null })
  owner!: Types.ObjectId | null;

  @Prop({ type: String, default: null })
  guestId!: string | null;

  /** Generated by the editor, so a design keeps its id across a sign-in. */
  @Prop({ required: true })
  documentId!: string;

  @Prop({ required: true, trim: true })
  name!: string;

  @Prop({ required: true })
  schemaVersion!: number;

  @Prop({ required: true })
  kind!: string;

  @Prop({ type: MongooseSchema.Types.Mixed, required: true })
  size!: unknown;

  @Prop({ required: true })
  bleed!: number;

  @Prop({ required: true })
  safeArea!: number;

  @Prop({ type: String, default: null })
  templateId!: string | null;

  /** Serialized Fabric scenes, one per side; opaque to the API. */
  @Prop({ type: MongooseSchema.Types.Mixed, required: true })
  sides!: unknown;

  /**
   * A small JPEG data URL of the front, rendered by the editor.
   *
   * Metadata about the design rather than part of it: it is what makes the
   * designs list legible without shipping every scene, so it rides in the
   * summary and stays out of the document the canvas loads.
   */
  @Prop({ type: String, default: null })
  thumbnail!: string | null;

  @Prop({ required: true })
  createdAt!: string;

  @Prop({ required: true })
  updatedAt!: string;
}

export type DesignDocument = HydratedDocument<Design>;

export const DesignSchema = SchemaFactory.createForClass(Design);

/*
 * One design per id per owner. Partial filters rather than `sparse`, because
 * sparse still indexes explicit nulls and every guest-owned row would then
 * collide with every other on a null `owner` — the same trap the choto-url
 * backend hit with googleId.
 */
DesignSchema.index(
  { owner: 1, documentId: 1 },
  { unique: true, partialFilterExpression: { owner: { $type: "objectId" } } },
);

DesignSchema.index(
  { guestId: 1, documentId: 1 },
  { unique: true, partialFilterExpression: { guestId: { $type: "string" } } },
);
